# Generated by Django 4.1 on 2022-09-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.TextField(max_length=50)),
                ('st_enrollment', models.TextField(max_length=20)),
                ('st_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
